#!/usr/bin/env zsh

# iOS DanXi 自动打包
# KYLN24

if [ $# -eq 1 ] && [ "$1" == "pre" ]; then
  release="pre-release"
else
  release="release"
fi

echo Building..
flutter build ios --no-codesign
echo Build Done.

echo Archieving..
cd build/ios/iphoneos || return
version=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" Runner.app/Info.plist)
name="DanXi-"${version}"-"${release}".ios.ipa"
mkdir Payload
cp -rf Runner.app Payload/DanXi.app
ditto -c -k --sequesterRsrc --keepParent Payload "${name}"
md5sum "${name}" >"${name}"".md5sum"
echo Made IPA package at build/ios/iphoneos/"${name}"
rm -rf Payload
echo Archieve Done.

cd ../../..

echo All Done.
