name: Automated-CI-Windows

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for release. If set to nightly, the release will be a pre-release."
        required: false
        default: nightly

jobs:
  Automated-CI-Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      #      - name: Install MSVC Build Tools
      #        uses: microsoft/setup-msbuild@v1.0.2
      #        with:
      #          vs-version: '16.0'
      #          architecture: 'x64'

      - name: Prepare Flutter Dependencies
        run: |
          flutter pub get
          flutter pub global activate intl_utils
          flutter pub global run intl_utils:generate

      - name: Generate Models
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Executable
        run: |
          flutter build windows --release

      - name: Package Executable
        run: 7z a -r -sse ..\..\..\..\build\app\app-release.zip *
        working-directory: build\windows\runner\Release

      - if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name != 'nightly'
        name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/app-release.zip
          prerelease: false
          tag_name: ${{ github.event.inputs.tag_name }}
          name: Release ${{ github.ref }}
          generate_release_notes: true
          fail_on_unmatched_files: true

      - if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name == 'nightly'
        name: Release Nightly
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/app-release.zip
          prerelease: true
          tag_name: nightly
          name: Nightly build
          generate_release_notes: true
          fail_on_unmatched_files: true
